### ISSUE TITLE
exe file for windows says failed to initilise graphical_interface. Or does nothing.

### ISSUE THREAD

**Issue by ritwikagrawal1228** [MartinM98/Handwriting-synthesis-with-the-help-of-machine-learning#103]
Hello. I installed Teseract 5 ocr seperatly then tried running the scriptarum.exe file. Once it showed an error called failed to initialise graphical interfsce. And then it shows nothing now.

I have tried rebooting and re-downloading. Still nothing

**Comment by Walczi123** [comment]
Hmm... Maybe that's problem with WxPython but did you check our thesis appendix?

**Comment by ritwikagrawal1228** [comment]
I did a pip install of the all the requirements then used the exe from zip. It worked fine.

I feel that this works only for lower number of characters since its really tolling on the machine.

There was a paper from 1995, where synthesising handwriting with variable lengths of character, spacing, etc was used and for each font character multiple models were used. 

There is one online tool called Scryptaliser that uses similar techniques as of that paper.

**Comment by zbartkus3150** [comment]
We are glad that you managed to make it work.
Unfortunately, the long string of characters will take appropriately more time to render, since each letter is processed individually. There exist a workaround for this issue which is the option to use GPU to either train the new model or render the letters. It requires installing additional software (CUDA) and only works for specific graphic cards due to TensorFlow compatibility. 
The reason why we did not use a more sophisticated method like the one you mentioned is that this project was to be completed in a specific time frame, thus we had to make some compromises in functionality and performance.
